branches:
  dev:
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - test
          - build-and-push
      required_signatures: true
      required_linear_history: true
      required_conversation_resolution: true
      allow_force_pushes: false
      allow_deletions: false
      include_administrators: true

  develop:
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts:
          - test
      required_conversation_resolution: true
      include_administrators: true 