global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']

  - job_name: 'asr'
    static_configs:
      - targets: ['asr:8001']

  - job_name: 'translation'
    static_configs:
      - targets: ['translation:8002']

  - job_name: 'tts'
    static_configs:
      - targets: ['tts:8003']

  - job_name: 'banking'
    static_configs:
      - targets: ['banking:8004'] 