models:
  dolphin:
    model_id: "cognitivecomputations/dolphin-2.6-mixtral-8x7b"
    device: "cuda"
    dtype: "float16"
    max_length: 2048
    temperature: 0.7
    top_p: 0.9
    repetition_penalty: 1.1
  
  banking:
    model_id: "microsoft/DialoGPT-medium"
    device: "cuda"
    dtype: "float16" 