name: ML Service Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          
      - name: Run tests
        run: |
          pytest tests/ --cov=app
          
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Digital Ocean Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/ml-services/api:${{ github.sha }}
            registry.digitalocean.com/ml-services/api:latest
          cache-from: type=registry,ref=registry.digitalocean.com/ml-services/api:buildcache
          cache-to: type=registry,ref=registry.digitalocean.com/ml-services/api:buildcache,mode=max
          
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Save kubeconfig
        run: doctl kubernetes cluster kubeconfig save ml-cluster
        
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/ml-service ml-service=registry.digitalocean.com/ml-services/api:${{ github.sha }}
          kubectl rollout status deployment/ml-service 